default: &default
  adapter: sqlite3
  # render デプロイのためにpassを追加
  password: IwNPaPnhrbhyMHLeWUlq9zDnz39BpTzZ
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # usernameを追加
  username: sample_app_production_9y97_user

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
