default: &default
  adapter: sqlite3

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
    # usernameを追加
  username: root
    # render デプロイのためにpassを追加
  password: IwNPaPnhrbhyMHLeWUlq9zDnz39BpTzZ
    # hostを追加
  host: localhost
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
